### ISSUE TITLE
Media manager for images and video content

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/rms-app#11]
Integrated sub-workspace for iamge and video link management.

**Comment by potzenheimer** [comment]
Todo: video link form and setup code. Since we have not planed a video integration in our preview json boilerplate we need to set the part up directly

**Comment by bumblebee831** [comment]
Und wie soll die Hilfe deiner Meinung nach aussehen?

**Comment by potzenheimer** [comment]
Hauptsächlich wollte ich die verfügbaren Keywords von Huboard testen ;)

**Comment by bumblebee831** [comment]
ok

**Comment by potzenheimer** [comment]
Hier bleibt die Frage nach der Implementierung des videos in den Stellplatz noch unbeantwortet. Aber dass diese angelegt werden können über ein Backend ist ja auch schon mal was.
