### ISSUE TITLE
Add missing translations to autogenerated templates and views 

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#15]
## missing translations

- [x] Startseite  https://d2.ade25.de/ nach Login: Authenticated user notice - Being present when authenticated this section should serve as a trigger for hiding the default banner image block and replace it with user specific content like a prominent link to the user acount workspace 
- [x] Startseite http://d2.ade25.de/: Signup call to action - Acount incentive Register to the appliction 
- [x] Workspace: TODO: communicate which caravan site we are editing and provide basic user actions like a password change, signout and content/authentication audit

## wordsmith

- [x] Anmeldung / korrekt wäre: Geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein, um sich anzumelden oder ein neues Benutzerkonto zu erstellen.

**Comment by potzenheimer** [comment]
Use actual checkboxes as a todo list by adding '[ ]'

**Comment by potzenheimer** [comment]
Temporärer Block "Login Frontpage" wird mit der bereits im Mockup vorhandenen call to action card ersetzt
