### ISSUE TITLE
Add static pages via CMS

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#16]
**Einzelansicht:** 
- [x] "weitere Bilder" geht nicht
- [x] "Kontakt" geht nicht

**Anmeldung:**
- [x] https://d2.ade25.de/datenschutz geht nicht
- [x] https://d2.ade25.de/agb geht nicht

**Footerlinks generell**

Alle statischen Inhalte wie z.B. Impressum, AGB, Kontakt usw sollten via CMS angelegt werden.
Die Inhalte des Footer Dummy sollten imselben Schritt am Besten bereinigt werden

**Comment by potzenheimer** [comment]
Das sind 2 verschiedene Themen:

die Caravan Site view brauch weitere Erweiterungen *gallery-view* und *inquiry-form*.

Die statischen Seiten wie Impressum/AGB/was auch immer, müssen via CMS angelegt werden. Denke das ist ein eigenes Issue

**Comment by potzenheimer** [comment]
Könnt ihr euch bitte um die statischen Inhalte via CMS kümmern? D.h. alle notwendigen Inhalte anlegen und den footer der Seite entsprechend anpassen/bereinigen?
