### ISSUE TITLE
Member signup process and workspace creation

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/rms-app#2]
This isseue involves 2 seperate steps:

1. Backport and simplify the existing implementations done for HfPH
2. Integrate global process handler that allows for smooth registration processes

**Comment by kreativkombinat** [comment]
Hallo, Guten Tag, Moin, Grüß Gott! What's up?

**Comment by potzenheimer** [comment]
Ich teste mal die Verwendung von Github zur Verwaltung der Projekt Todos, um mal ein Gefühl dazu zu entwickeln.

**Comment by kreativkombinat** [comment]
Ok verstehe, bin dabei!
