### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#20]

**Comment by bumblebee831** [comment]
'[ ]' https://d2.ade25.de/: Bilder der Startseite auch verlinken

**Comment by potzenheimer** [comment]
Das ist ein Grenzfall: wir haben eigentlich kein Bild, da diese per "lazy load" nachgeladen werden, also würden wir einen Link implementieren der 1x1 Pixel gross ist. Sollten jetzt die Bilder nicht oder nicht schnell genug nachgeladen werden bei Edge Mobilverbindung, dann haben wir versteckte Klickbereiche, die Benutzer beim Scrollen mit dem Finger auf einem Tablet versehentlich erwischen könnten. Das wäre dann extrem verwirrend und ein Usability Problem. Bin mir nicht sicher, ob wir dieses Risiko in Kauf nehmen sollten

**Comment by kreativkombinat** [comment]
Ich denke wir sollen das in echtzeit testen und dann ggf reagieren.

**Comment by kreativkombinat** [comment]
Allerdings gänzlich auf "hold" macht das echtzeittesten unmöglich!

**Comment by potzenheimer** [comment]
OK - ich denke das kann ich abgeben. Frontpage view ist im *rms.caravansites* package.
