### ISSUE TITLE
Fehlermeldung bei 1. Stellplatzansicht

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#22]

**Comment by bumblebee831** [comment]
https://d2.ade25.de/stellplatz-am-dom -> bringt immer noch Fehler

**Comment by potzenheimer** [comment]
schon mal via https://d2.ade25.de/stellplatz-am-dom/@@json-view die Daten überprüft? kann eigentlich nur einen inhaltlichen grund haben, warum das hier scheitert.

**Comment by bumblebee831** [comment]
Ich hatte nichts mehr daran verändert. Seit meinen Änderungen (und da habe ich jeden Stellplatz geprüft) wurden keine inhaltlichen Änderungen mehr vorgenommen.

**Comment by potzenheimer** [comment]
Auf den ersten Blick würde ich sagen unter **contact** fehlt der operator
