### ISSUE TITLE
Betreiberwebseite in neuem Tab öffnen

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#34]
Feld "Webseite" beim Stellplatz: Ziellink in neuem Tab öffnen und Beschreibung des Feldes ergänzen um "Link öffnet in neuem Fenster"

**Comment by potzenheimer** [comment]
Ich würde soweit gehen und die URL in einen Link *Webseite besuchen* oder so umbennen, da wir sowieso für Small Device Display keinen Platz für die langen URIs haben und desweiteren das ganze etwas enheitlicher aussieht.
