### ISSUE TITLE
Umweltzone / Auswahl ändern

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#35]
Feld Umweltzone soll folgende Auswahlmöglichkeiten haben:
nein
grün
grün-gelb
Sondergenehmigung

**Comment by bumblebee831** [comment]
Danke dir. Könnte man bitte die Werte noch übersetzen?

**Comment by potzenheimer** [comment]
Die translation machinery ist eigentlich korrekt konfiguriert. Wo sind die Werte nicht überstetzt? Edit/View?
