### ISSUE TITLE
Stellplatzanzeige Sortierung

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#36]
Die Stellplätze sollen nach Ihrer Postleitzahl sortiert dargestellt werden. Aufsteigend.

**Comment by potzenheimer** [comment]
Gibt es eine spezielle Begründung für diese nicht unbedingt naheliegende Idee? 

Hintergrund:

Ich würde eventuell in einem Ausbauschritt verschiedenen Sortiermöglichkeiten anbieten (dann auch immer mit Umschaltbarer Sortierreihenfolge). 

Aber zum Start einer Plattform wäre die manuelle Sortierung wohl die beste, da ich so die Möglichkeit habe die besten und schönsten Stellplätze an vorderster Front zu präsentieren. Ich denke der erste Eindruck ist zum Launch sehr viel entscheidender als die Lage eines Stellplatzes.

**Comment by bumblebee831** [comment]
Grund hierfür ist:
Sie wollten UNBEDINGT eine Suche. Das konnten wir ihnen ausreden, weil es Quatsch ist. Eine Sortierung allgemein fänden Sie aber dennoch sehr wichtig, weshalb sie sich im Termin auf die PLZ geeinigt haben.

**Comment by potzenheimer** [comment]
An eine Sortierung nach Postleitzahl hätte ich als letztes gedacht, folglich ist das i.A. eigentlich garnicht möglich bzw fällt mir gerade nicht ein, wie ich das irgendwie sinnvoll implementieren kann. 

 Das Konzept war eigentlich, die Suche bei einer relevanten Anzahl von Inhalten zu implementieren und dann eben auch über die Indizierung der Inhalte nachzudenken. Sind die Inhalte indiziert, also durchsuchbar gespeichert, dann lassen sich diese auch in bestimmter Form abrufen (wie: alle Inhalte sortiert nach Index "zipcode"). Das ist aber (noch) nicht implementiert, weil die Prio 1 bei einem Launch mit einem neuen Produkt *immer* auf Aquise liegen muss.

**Comment by potzenheimer** [comment]
Müssen wir diskutieren/besprechen. Mir fällt auch keine pragmatische Lösung ein.

**Comment by potzenheimer** [comment]
Nach Besprechung werden wir/ich nun maximal 4h dafür aufwenden eine möglichst einfache Lösung für dieses Problem zu finden. Ansatz: einen indexer für die wichtigsten Daten eines Stellplatzes erstellen oder ein komplexes RAM-Cache setup für die liste der Stellplätze verwenden und dann entsprechend die Daten aus dem Cache lesen.
