### ISSUE TITLE
Bestätigungsemail ändern

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#37]
Bestätigungse-mail muss ergänzt werden:
- Hinweis auf die AGB und die Zustimmung
- Hinweis zur Preisliste und der Konsequenz (Eliminierung nach Erreichen der 100 ersten Mitglieder) bei Nichtausfüllen etc.

**Comment by bumblebee831** [comment]
Ich mache gerne den Text. Sag mir nur wo und wie.

**Comment by potzenheimer** [comment]
Diese E-Mail dient dazu, die bei der Registrierung verwendete E-Mail-Adresse auf Ihre Gültigkeit zu überprüfen. Dies ist eine wichtige **Funktion**, da die E-Mail-Adresse die einzige valide Möglichkeit darstellt, einen registrierten Stellplatzbetreiber zu identifizieren.  Da sollte möglichst wenig Ballast dabei sein.

Ausserdem wird die E-Mail erst nach erfolgreicher Registrierung versandt, d.h. ein Hinweis auf das Akzeptieren von AGB ist zuspät. Der muss - wir auch vorhanden - vorher eingebunden werden. Dasselbe gilt auch für alle anderen *wichtigen* Informationen: eine wesentliche Funktion (Benutzerkonto verifizieren) kann nicht gelichzeitig eine weitere Funktion erfüllen und/oder Marketinginstrument sein (Preisliste). Das ist die falsche Stelle.

Wir können über eine gesonderte Info-E-Mail z.b.  beim Veröffentlichen eines Stellplatzes nachdenken. Das wäre aber ein Extrafeature meine ich.

**Comment by bumblebee831** [comment]
Ich muss den Login-Text eh nochmal bearbeiten. Dort kann auf die AGB verwiesen werden. Aktuell gibt es keinen Hinweis auf die Bezahlung etc. Das war der einfachste Weg. Ich bekomme die aber auch nicht dazu, nochmal Geld für sowas zu investieren. Zunächst wird ein neuer Hostingvertrag und die NL große Hürden, die zu bewerkstelligen sind. Also wenn du der Meinung bist, dass die E-Mail nicht geht, dann muss der Login ausreichen. Mehr geht grad nicht.

**Comment by potzenheimer** [comment]
https://d2.ade25.de/@@signup-form hat wie das üblich ist einen Hinweis auf die AGB. Ein Hinweis auf eventuell anfallende Kosten gehört an die Stelle, an der die kostenpflichtigen Funktionen sind, ergo: zum Anlegen/Veröffentlichen eines Stellplatzes.

**Comment by bumblebee831** [comment]
ok. Dann halt da.
