### ISSUE TITLE
Fehler nach Anmeldung

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/rms-app#39]
Logged man sich mit einem bestehenden Account ein zweites Mal ein, kommt eine Fehlermeldung. Unabhängig von einem Admin und einem normalen Betreiberaccount. https://d2.ade25.de/@@signup-form

**Comment by potzenheimer** [comment]
Die Anmeldung funktioniert soweit problemlos. Allerdings ist das aktualisieren des Benutzeracounts mit der `login_time` nicht möglich, da der eben authentifizierte User nicht oder noch nicht aufgerufen werden kann. Ich vermute der `processLogin` task braucht schlichtweg zu lange.

Ich versuche den aus dem Formular übergebenen **__ac_name**  anstelle von `user.getId()` einzusetzen - eventuell genügt das auch bereits. Eine weitere Überlegung wäre den Wert für *last_login* zu ignorieren, da die bereits mit bedachte Funktion "History" wahrscheinlich eh nie implementiert werden wird :)
