### ISSUE TITLE
Media Manager add image form error

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/rms-app#40]
When accessing the media manager *add* form the following error occures:

```
Module ZPublisher.Publish, line 138, in publish
   Module ZPublisher.mapply, line 77, in mapply
   Module ZPublisher.Publish, line 48, in call_object
   Module z3c.form.form, line 218, in __call__
   Module plone.z3cform.fieldsets.extensible, line 59, in update
   Module plone.z3cform.patch, line 30, in GroupForm_update
   Module z3c.form.group, line 145, in update
   Module plone.app.z3cform.csrf, line 21, in execute
   Module z3c.form.action, line 98, in execute
   Module z3c.form.button, line 315, in __call__
   Module z3c.form.button, line 170, in __call__
   Module rms.caravansites.mediamanager, line 121, in handleApply
   Module rms.caravansites.mediamanager, line 135, in applyChanges
   Module rms.caravansites.mediamanager, line 106, in existing_images
   Module OFS.Traversable, line 317, in restrictedTraverse
   Module OFS.Traversable, line 300, in unrestrictedTraverse
   __traceback_info__: ([], '@@folderListing')

AttributeError: @@folderListing
```

**Comment by potzenheimer** [comment]
In einer lokalen Kopie ist der Fehler nicht nachvollziehbar, was die Sache nicht nur mysteriös sondern auch schwer zu beheben macht. Ich teste mal nochmal mit meinem User Online

**Comment by bumblebee831** [comment]
Leider immer noch nicht behoben. 
Bei Stellplatz Kamerun ein weiteres Bild hinzugefügt:

https://d2.ade25.de/ws/223dd504c171454791178088c7c93d4a/@@image-factory/13aac402456c448b9a55ac904aa7bc48

Fehler

**Comment by bumblebee831** [comment]
Außerdem lassen sich die Bildtitel nicht mehr ändern. Das sieht dann im Fall von Kamerung etwas dämlich aus https://d2.ade25.de/wohnmobilpark-kamerun/@@gallery-view

**Comment by potzenheimer** [comment]
Fehler ist nicht nachvollziehbar - vermute das es sich hier um ein User-spezifisches Problem handelt und/oder ein context Problem, dass nicht in jedem Fall auftritt - letzteres versuche ich mal via `memoize` decorator auszuschliessen, so dass die notwendigen Variablen für die Lebensdauer des Request schlichtweg zwischengespeichert werden.

**Comment by potzenheimer** [comment]
Das Thema *Bildtitel* betrifft die Image Edit Form und ist somit ein eigenes Thema (siehe Folgeticket)
