### ISSUE TITLE
Update assignment don't work

### ISSUE THREAD

**Issue by kreativkombinat** [a25kk/rms-app#60]
2 mal lokal getestet mit dem resultat: 
Ihrem Benutzerkonto ist noch kein Stellplatz zugeordnet. Verwenden Sie die Schaltfläche Stellplatz anlegen, um mit der Bearbeitung Ihres Stellplatzes zu beginnen. 
Update bringt keinen fehler, allerdingt wird dem User nach dem login nichts zugewiesen!

**Comment by potzenheimer** [comment]
Bin mir nicht sicher, wie das am Besten zu debuggen ist.  Die Zuweisung schreibt eigentlich nur die workspace ID in die Member Properties

```python
user.setMemberProperties(mapping={'rvs': item_uid})
```
Nachdem im Anschluss nichts ausgeführt wird, als das Auslesen dieser Daten beim Login wie gehabt, kann es eigentlich keinen Unterschied machen, ob der Stallplatz erstellt oder zugewiesen wurde. Ich kann das nochmal durchspielen mit einem neuen lokalen Benutzer.

**Comment by kreativkombinat** [comment]
Ich kann auch gerne nochmal lokal testen falls das sinn macht

**Comment by potzenheimer** [comment]
Testet:

Neuen Benutzer regististriert -> workspace ID aus der Willkommens-E-Mail kopiert und einen bestehenden Stellplatz zugewiesen

**Comment by potzenheimer** [comment]
Denke dieses Issue kann mittlerweile geschlossen werden
